# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/steve/projects/drift-scheme

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/steve/projects/drift-scheme

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steve/projects/drift-scheme/CMakeFiles /home/steve/projects/drift-scheme/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steve/projects/drift-scheme/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named drift_scheme_test

# Build rule for target.
drift_scheme_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drift_scheme_test
.PHONY : drift_scheme_test

# fast build rule for target.
drift_scheme_test/fast:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/build
.PHONY : drift_scheme_test/fast

context.o: context.cc.o

.PHONY : context.o

# target to build an object file
context.cc.o:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/context.cc.o
.PHONY : context.cc.o

context.i: context.cc.i

.PHONY : context.i

# target to preprocess a source file
context.cc.i:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/context.cc.i
.PHONY : context.cc.i

context.s: context.cc.s

.PHONY : context.s

# target to generate assembly for a file
context.cc.s:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/context.cc.s
.PHONY : context.cc.s

env.o: env.cc.o

.PHONY : env.o

# target to build an object file
env.cc.o:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/env.cc.o
.PHONY : env.cc.o

env.i: env.cc.i

.PHONY : env.i

# target to preprocess a source file
env.cc.i:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/env.cc.i
.PHONY : env.cc.i

env.s: env.cc.s

.PHONY : env.s

# target to generate assembly for a file
env.cc.s:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/env.cc.s
.PHONY : env.cc.s

lex.o: lex.cc.o

.PHONY : lex.o

# target to build an object file
lex.cc.o:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/lex.cc.o
.PHONY : lex.cc.o

lex.i: lex.cc.i

.PHONY : lex.i

# target to preprocess a source file
lex.cc.i:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/lex.cc.i
.PHONY : lex.cc.i

lex.s: lex.cc.s

.PHONY : lex.s

# target to generate assembly for a file
lex.cc.s:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/lex.cc.s
.PHONY : lex.cc.s

lib.o: lib.cc.o

.PHONY : lib.o

# target to build an object file
lib.cc.o:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/lib.cc.o
.PHONY : lib.cc.o

lib.i: lib.cc.i

.PHONY : lib.i

# target to preprocess a source file
lib.cc.i:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/lib.cc.i
.PHONY : lib.cc.i

lib.s: lib.cc.s

.PHONY : lib.s

# target to generate assembly for a file
lib.cc.s:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/lib.cc.s
.PHONY : lib.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/main.cc.s
.PHONY : main.cc.s

parse.o: parse.cc.o

.PHONY : parse.o

# target to build an object file
parse.cc.o:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/parse.cc.o
.PHONY : parse.cc.o

parse.i: parse.cc.i

.PHONY : parse.i

# target to preprocess a source file
parse.cc.i:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/parse.cc.i
.PHONY : parse.cc.i

parse.s: parse.cc.s

.PHONY : parse.s

# target to generate assembly for a file
parse.cc.s:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/parse.cc.s
.PHONY : parse.cc.s

variant.o: variant.cc.o

.PHONY : variant.o

# target to build an object file
variant.cc.o:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/variant.cc.o
.PHONY : variant.cc.o

variant.i: variant.cc.i

.PHONY : variant.i

# target to preprocess a source file
variant.cc.i:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/variant.cc.i
.PHONY : variant.cc.i

variant.s: variant.cc.s

.PHONY : variant.s

# target to generate assembly for a file
variant.cc.s:
	$(MAKE) -f CMakeFiles/drift_scheme_test.dir/build.make CMakeFiles/drift_scheme_test.dir/variant.cc.s
.PHONY : variant.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... drift_scheme_test"
	@echo "... context.o"
	@echo "... context.i"
	@echo "... context.s"
	@echo "... env.o"
	@echo "... env.i"
	@echo "... env.s"
	@echo "... lex.o"
	@echo "... lex.i"
	@echo "... lex.s"
	@echo "... lib.o"
	@echo "... lib.i"
	@echo "... lib.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... variant.o"
	@echo "... variant.i"
	@echo "... variant.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

