(print "Hello from drift::scheme. ")
(println "I didn't use a new line on the previous statement but I did for this one : (")
(println "Here's the sum of 1 2 3 and 4: " (+ 1 2 3 4))
(println "If you pass zero to the if statemnent you'll see blarg, else just arg: " (if 1 "arg" "blarg"))
(define megaman "MY name is megaman")
(println "Our friend mega man's name is: " megaman)
(println "Mega man's phrase twice: " (* megaman 2))
(println "Value of pi: " pi)
(set! megaman "Cutboy")
(println "Mega man changed his name to: " megaman)